version: "2.0"
services:
  cart:
    build: .
    ports:
      - "9292:9292"
    volumes:
      - "./local-db:/db"
    entrypoint: scripts/start.sh
  api-doc:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment: 
      URL: "http://localhost:9292/api/docs"